# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Version
        id: set_version
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2 

      - name: Start Docker Compose Services 
        run: | 
          docker compose up -d --build

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/app:${{ env.VERSION }}
          format: template
          template: "@/contrib/sarif.tpl"
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          scan-type: image
          scan-ref: .
          ignore-unfixed: false
          vuln-type: os,library
          list-all-pkgs: false
        env:
          VERSION: 20250319103247

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
